#!/usr/bin/env python2

# Imports
import sshreader

hosts = ['host1.example.com', 'host2.example.com']

# Create a list of ServerJob objects with commands to run on each server
serverjobs = list()
for host in hosts:
    # Create the ServerJob object with the shell commands you want to run
    serverjobs.append(sshreader.ServerJob(host, ['uname -a', 'uptime'], username='myuser', password='password'))

# sshread the list of ServerJobs as quickly as possible!
# setting pcount and tcount to 0 will let sshreader figure out the number of processes and threads to spawn for best
# results.
results = sshreader.sshread(serverjobs, pcount=0, tcount=0, progressbar=True)

# Output the results from each job
for result in results:
    result.print_results()
