[tox]
envlist = py27,py36

[testenv]
changedir=tests
commands=discover
deps=discover

[testenv:docs]
basepython=python
changedir=docs/source
deps=-rrequirements.txt
commands=
    sphinx-build -b html -d {envtmpdir}/doctrees .  {envtmpdir}/html
